### ISSUE TITLE
Ejection should not trigger CSAR or pilot spawn inside base radius

### ISSUE THREAD

**Issue by Winston2108** [ModernColdWar/RedStormRising#85]
When the CSAR script handles an ejection, it needs to check if it's inside a base defence zone and not spawn the pilot, changing the message to be just to the group saying either rescued (if at a friendly base) or captured (if at an enemy base).

**Comment by alxz3** [comment]
get base radius
get base site

if ejected pilot inside base radius and base is not same coalition run script
else dont run script

*maybe give base radius 1nm+ range because 20meters next to enemy base would be also dump

Need fix asap as downed pilots are able to capture base/farp - have seen it been abused at least twice

**Comment by Winston2108** [comment]
@alxz3 it's going to be tied to the capture radius, and as the description says:

* Friendly base - no CSAR, life point not lost
* Enemy base - no CSAR, life point lost as normal

**Comment by Winston2108** [comment]
Ejecting at an enemy base may trigger a snarky message if I have time.

**Comment by Winston2108** [comment]
Fixed in `3585c45`.  If closest base is within 20km and is enemy, no CSAR pilot/mission.  Ejecting at "home" still triggers a CSAR mission as I think that's desirable - it's a nice thing to eject right on top of slingers if you can.
